app/Http/routes.php
<?php

/** Admin **/
Route::group([
    'prefix' => 'admin',
], function () {
    Route::get('dashboard', 'AdminController@admin')->name('admin.dashboard');

    Route::resource('advertisement', 'AdvertisementController');
    Route::resource('slider', 'SliderController');

    Route::resource('user', 'UserController');
    Route::put('admin/userseen/{user}', 'UserController@updateSeen');
    Route::get('week-blogger', 'UserController@weekBlogger')->name('admin.week_blogger');
    Route::post('/new-top-blogger', 'UserController@newTopBlogger')->name('admin.new_top_blogger');
    Route::post('/live-search', 'UserController@liveSearch')->name('admin.user_search');
    Route::get('/sticky-post', 'AdminController@stickyPost')->name('admin.sticky_post');
    Route::post('/new-sticky-post', 'AdminController@newStickyPost')->name('admin.new_sticky_post');

    Route::resource('product', 'ProductController', ['names' => [
        'index' => 'product.list',
        'create' => 'product.create',
        'store' => 'product.store',
        'edit' => 'product.edit',
        'update' => 'product.update',
        'destroy' => 'product.destroy'
    ]]);

    /** Shop (boutique) */

    Route::resource('shop/category', 'ProductCategoryController', ['names' => [
        'index' => 'product_category.index',
        'create' => 'product_category.create',
        'store' => 'product_category.store',
        'edit' => 'product_category.edit',
        'update' => 'product_category.update',
        'destroy' => 'product_category.destroy',
        'show' => 'product_category.show'
    ]]);

    Route::post('/vacancy-delete', [
        'uses' => 'ProfileController@deleteVacancy',
        'middleware' => 'employer'
    ]);

    Route::get('vacancy', [
        'uses' => 'VacancyController@indexOrder',
        'as' => 'admin.vacancy'
    ]);

    Route::put('vacancyactive/{id}', [
        'uses' => 'VacancyController@updateActive',
    ])->name('admin.vacancyactive');

    Route::put('vacancyseen/{id}', [
        'uses' => 'VacancyController@updateSeen'
    ])->name('admin.vacancyseen');

    Route::put('/translate/{id}', 'TranslationController@update')->name('admin.trans.update');
    Route::get('/translate/{id}', 'TranslationController@translate')->name('admin.trans.translate');
    Route::post('/translate/{id}', 'TranslationController@store')->name('admin.trans.store');
    Route::get('/translations/{id}', 'TranslationController@translations')->name('admin.trans.index');
    Route::get('/translate/{id}/edit', 'TranslationController@edit')->name('admin.trans.edit');

    Route::get('blog/order', 'BlogController@indexOrder')->name('admin.blog.order');
    Route::put('postseen/{id}', 'BlogController@updateSeen')->name('admin.postseen');
    Route::put('postactive/{id}', 'BlogController@updateActive')->name('admin.postactive');
    Route::put('postlanguage/{id}', 'BlogController@updateLanguage')->name('admin.postlanguage');
    Route::get('post/see/{category}/{id}', 'BlogController@see')->name('admin.post.see');
    Route::resource('blog', 'BlogController', ['except' => ['create', 'store']]);
});

Route::group(['prefix' => LaravelLocalization::setLocale(),'middleware' => [ 'localeSessionRedirect', 'localizationRedirect']], function() {
    // Profile

    Route::resource('profile', 'ProfileController');

    Route::group([
        'prefix' => 'profile',
    ], function () {
        Route::get('post/create', 'BlogController@create')->name('profile.post.create');
        Route::post('post/store', 'BlogController@store')->name('profile.post.store');
        Route::get('profile/vacancies/', 'ProfileController@myVacancies');
        Route::post('/post-delete', ['uses' => 'ProfileController@deletePost', 'middleware' => 'blogger'])->name('profile.post.delete');
        Route::get('/activate-post/{id}', ['uses' => 'ProfileController@activatePost', 'middleware' => 'blogger'])->name('profile.post.activate');
    });

// Home
    Route::get('/', [
        'uses' => 'HomeController@index',
        'as' => 'home'
    ]);


// Business
    Route::get('business/{param}/', 'PageController@show')->name('business.page');

// Blog
    Route::get('blog/tag', 'BlogController@tag');
    Route::get('blog/search', 'BlogController@search');
    Route::get('/articles/{category}/{title}', 'BlogController@show')->name('articles.post.show');


    Route::resource('/articles', 'CategoryController', ['prefix' => 'articles', 'names' => [
        'index' => 'category.index',
        'show' => 'category.show',
        'create' => 'category.create',
        'store' => 'category.store',
        'edit' => 'category.edit',
        'update' => 'category.update',
        'destroy' => 'category.destroy'
    ]]);

    Route::get('/articles/{name}/category/{subcategory}', 'CategoryController@showSubcategory')->name('subcategory.show');


// Fashion-job

    Route::post('fashion-job/search', 'VacancyController@search');
    Route::get('/fashion-job/confirmation', 'VacancyController@confirmation');
    Route::resource('company', 'CompanyController');
    Route::resource('fashion-job', 'VacancyController');

// Boutique

    Route::get('boutique/category/{hierarchy}', 'ProductCategoryController@show')->where('hierarchy', '(.*)?')->name('boutique');
    Route::get('boutique/{hierarchy}/{slug}', 'ProductController@show')->where('hierarchy', '(.*)?')->name('product.show');
    Route::post('/boutique/product/buy', ['uses' => 'ProductController@buyProduct', 'as' => 'product.buy']);
    Route::post('admin/product/images/{id}/delete', ['uses' => 'ProductController@deleteImage', 'as' => 'product.image.delete']);
    Route::post('admin/product/thumb/{id}/delete', ['uses' => 'ProductController@deleteThumb', 'as' => 'product.thumb.delete']);


// User
    Route::get('user/sort/{role}', 'UserController@indexSort');
    Route::get('user/roles', 'UserController@getRoles');
    Route::post('user/roles', 'UserController@postRoles');


// Auth
    Route::controllers([
        'auth' => 'Auth\AuthController',
        'password' => 'Auth\PasswordController'
    ]);

    Route::get('/email-confirmation', 'Auth\AuthController@confirmation');
    Route::get('/resend-email', 'Auth\AuthController@getResend');


// Social networks auth

    Route::get('/facebook/{role?}', ['uses' => 'SocializeController@loginWithFacebook']);
    Route::get('/vkontakte/{role?}', ['uses' => 'SocializeController@loginWithVkontakte']);
    Route::get('/google/{role?}', ['uses' => 'SocializeController@loginWithGoogle']);
    Route::get('/twitter/{role?}', ['uses' => 'SocializeController@loginWithTwitter']);


// Social networks share
    Route::get('/share-twitter/{category}/{slug}/{title}/', function ($category, $slug, $title) {
        $link = URL::to('/') . '/blog/' . $category . '/' . $slug . '/';
        $share = Share::load($link, $title)->twitter();
        return redirect($share);
    });

    Route::get('/share-facebook/{category}/{slug}/{title}/', function ($category, $slug, $title) {
        $link = URL::to('/') . '/blog/' . $category . '/' . $slug . '/';
        $share = Share::load($link, $title)->facebook();
        return redirect($share);
    });

    Route::get('/share-pinterest/{category}/{slug}/{title}/', function ($category, $slug, $title) {
        $link = URL::to('/') . '/blog/' . $category . '/' . $slug . '/';
        $share = Share::load($link, $title)->pinterest();
        return redirect($share);
    });

//Subscribe
    Route::post('subscribe', 'NewsletterController@subscribe');

});

// Ajax actions
Route::post('/like', [
    'uses' => 'BlogController@upLike',
    'middleware' => 'auth'
]);

Route::post('/load-posts', [
    'uses' => 'CategoryController@loadPosts'
]);

Route::post('/load-subcat', [
    'uses' => 'CategoryController@loadSubcategories'
]);

Route::post('/buy-service', [
    'uses' => 'BlogController@buyService'
]);

Route::post('/save-profile', [
    'uses' => 'ProfileController@store',
    'middleware' => 'auth'
]);

Route::post('/save-company', [
    'uses' => 'CompanyController@store',
    'middleware' => 'employer'
]);

Route::post('/delete-company', [
    'uses' => 'CompanyController@destroy',
    'middleware' => 'employer'
]);

Route::post('/profile-posts', [
    'uses' => 'ProfileController@loadPosts',
    'middleware' => 'blogger'
]);

Route::post('/profile-vacancies', [
    'uses' => 'ProfileController@loadVacancies',
    'middleware' => 'employer'
]);

Route::post('/load-vacancies', [
    'uses' => 'VacancyController@loadVacancies'
]);

Route::post('/filter-vacancies', [
    'uses' => 'VacancyController@filterVacancies'
]);

Route::post('/search-vacancies', [
    'uses' => 'VacancyController@searchVacancies'
]);

Route::post('/get-city', [
    'uses' => 'VacancyController@getCity'
]);

Route::post('send-cv', 'VacancyController@sendCV');

/*
|--------------------------------------------------------------------------
| Max Upload File Size filter
|--------------------------------------------------------------------------
|
| Check if a user uploaded a file larger than the max size limit.
| This filter is used when we also use a CSRF filter and don't want
| to get a TokenMismatchException due to $_POST and $_GET being cleared.
|
*/
Route::filter('maxUploadFileSize', function()
{
    // Check if upload has exceeded max size limit
    if (! (Request::isMethod('POST') or Request::isMethod('PUT'))) { return; }
    // Get the max upload size (in Mb, so convert it to bytes)
    $maxUploadSize = 1024 * 1024 * ini_get('post_max_size');
    $contentSize = 0;
    if (isset($_SERVER['HTTP_CONTENT_LENGTH']))
    {
        $contentSize = $_SERVER['HTTP_CONTENT_LENGTH'];
    }
    elseif (isset($_SERVER['CONTENT_LENGTH']))
    {
        $contentSize = $_SERVER['CONTENT_LENGTH'];
    }
    // If content exceeds max size, throw an exception
    if ($contentSize > $maxUploadSize)
    {
        throw new GSVnet\Core\Exceptions\MaxUploadSizeException;
    }
});

app/Models/Slider.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Slider extends Model
{
    protected $table = 'slider';

    protected $fillable = array('id', 'post_id');

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function post()
    {
        return $this->belongsTo('App\Models\Post');
    }
}

app/Http/Controllers/SliderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Models\Slider;
use App\Models\Post;
use App\Repositories\BlogRepository;


class SliderController extends Controller
{

    protected $blog_gestion;

    /**
     * SliderController constructor.
     * @param BlogRepository $blog_gestion
     */
    public function __construct(BlogRepository $blog_gestion)
    {
        $this->blog_gestion = $blog_gestion;
        $this->middleware('admin');
    }

    /**
     * @return mixed
     */
    public function index()
    {
        $slider = Slider::with('post')->get();

        return view('back.slider.index', compact('slider'));
    }

    /**
     * @return mixed
     */
    public function create()
    {
        $url = config('medias.url');

        $posts = Post::where('original_id', 0)->orderBy('title', 'ASC')->where('active', 1)->lists('title', 'id');

        return view('back.slider.create', compact('url', 'posts'));
    }

    /**
     * @param Request $request
     * @return mixed
     */
    public function store(Request $request)
    {
        $slider = new Slider(); 
        $slider->post_id = $request->post;
        $slider->save();

        return redirect()->route('admin.slider.index');
    }

    /**
     * @param $id
     * @return mixed
     */
    public function show($id)
    {
        return redirect(\App::getLocale() . '/');
    }

    /**
     * @param $id
     * @return mixed
     */
    public function edit($id)
    {
        $slide = Slider::find($id);

        $posts = Post::where('original_id', 0)->orderBy('title', 'ASC')->lists('title', 'id');

        return view('back.slider.edit', compact('slide', 'posts'));
    }

    /**
     * @param Request $request
     * @param $id
     * @return mixed
     */
    public function update(Request $request, $id)
    {
        $slide = Slider::find($id);
        $slide->post_id = $request->post;
        $slide->update();

        return redirect()->route('admin.slider.index');
    }

    /**
     * @param $id
     * @return mixed
     */
    public function destroy($id)
    {
        $slide = Slider::find($id);
        $slide->delete();

        return redirect()->back();
    }
}

resources/views/back/slider/create.blade.php
@extends('back.template')
@section('title', "Create a slide")

@section('main')

    @include('back.partials.entete', ['title' => 'Add slider', 'icone' => 'fa fa-sliders', 'fil' =>'Slider'])

    @if(session()->has('ok'))
        @include('partials/error', ['type' => 'success', 'message' => session('ok')])
    @endif

    {!! Form::open(['route' => 'admin.slider.store', 'method' => 'post', 'enctype' => 'multipart/form-data']) !!}
        <div class="form-group">
            {!! Form::label('post', 'Post title:') !!}
            {!! Form::select('post', $posts, null, ['class' => 'form-control', 'required' => 'required']) !!}
        </div>
    <div class="form-group">
        {!! Form::submit('Add') !!}
    </div>
   {!! Form::close() !!}
@stop

resources/views/back/slider/edit.blade.php
@extends('back.template')

@section('title', "Edit the slide")

@section('main')

    @include('back.partials.entete', ['title' => 'Edit slider', 'icone' => 'fa fa-sliders', 'fil' =>'Slider'])

    {!! Form::open(['route' => ['admin.slider.update', $slide->id], 'method' => 'put',  'class' => 'form-horizontal panel']) !!}
    <div class="form-group">
        {!! Form::label('post', 'Post title:') !!}
        {!! Form::select('post', $posts, $slide->post->id, ['class' => 'form-control', 'required' => 'required']) !!}
    </div>
    <input type="hidden" name="_token" value="{{ csrf_token() }}">
    {!! Form::submit('Update') !!}
    {!! Form::close() !!}
@stop

resources/views/back/slider/index.blade.php
@extends('back.template')

@section('title', "Slider")

@section('main')
    @include('back.partials.entete', ['title' => 'Slider' . link_to_route('admin.slider.create', 'Slider add', [], ['class' => 'btn btn-info pull-right']), 'icone' => 'folder-open', 'fil' => 'Slider\Add'])

    @if(session()->has('ok'))
        @include('partials/error', ['type' => 'success', 'message' => session('ok')])
    @endif
        @if (count($slider) > 0)
            <div class="row col-lg-12">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th> Slide number </th>
                                <th> Category </th>
                                <th> Title </th>
                                <th> Author </th>
                            </tr>
                        </thead>
                        <tbody>
                            @include('back.slider.table')
                        </tbody>
                    </table>
                </div>
            </div>
        @endif
@stop

resources/views/back/slider/table.blade.php
@foreach ($slider as $key => $slide)
    <tr {!! session('statut') == 'admin'? 'class="warning"' : '' !!}>
        <td class="text-primary"><strong>{{ $key + 1 }}</strong></td>
        <td class="text-primary"><strong>{{ $slide->post->category->name }}</strong></td>
        <td class="text-primary"><strong>{{ $slide->post->title }}</strong></td>
        <td class="text-primary"><strong>{{ $slide->post->user->firstname . ' ' . $slide->post->user->lastname }}</strong></td>
    <td>{!! link_to('/','See' , ['class' => 'btn btn-success btn-block btn']) !!}</td>

    <td>{!! link_to_route('admin.slider.edit', 'Edit', [$slide->id], ['class' => 'btn btn-warning btn-block']) !!}</td>
        <td>
            {!! Form::open(['method' => 'DELETE', 'route' => ['admin.slider.destroy', $slide->id]]) !!}
                {!! Form::destroy('Destroy', 'Destroy') !!}
            {!! Form::close() !!}
        </td>
    </tr>
@endforeach

resources/views/back/slider/template.blade.php
@extends('back.template')

@section('main')

    @include('back.partials.entete', ['title' => 'Slider', 'icone' => 'pencil', 'fil' => link_to('slider', 'Slider') . ' / ' . 'Dashboard'])

    <div class="col-sm-12">
        @yield('form')

        {!! Form::open(['method' => 'UPDATE', 'url' => '/slider/' . $slide->id, 'enctype' => 'multipart/form-data']) !!}
         <div class="form-group">
            {!! Form::label('post', 'Post title:') !!}
            {!! Form::select('post', $posts, $slide->post, ['class' => 'form-control', 'required' => 'required']) !!}
            </div>
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            {!! Form::submit('Update') !!}
        {!! Form::close() !!}
    </div>
@stop