app/Http/routes.php
<?php

/** Admin **/
Route::group([
    'prefix' => 'admin',
], function () {
    Route::get('dashboard', 'AdminController@admin')->name('admin.dashboard');

    Route::resource('advertisement', 'AdvertisementController');
    Route::resource('slider', 'SliderController');

    Route::resource('user', 'UserController');
    Route::put('admin/userseen/{user}', 'UserController@updateSeen');
    Route::get('week-blogger', 'UserController@weekBlogger')->name('admin.week_blogger');
    Route::post('/new-top-blogger', 'UserController@newTopBlogger')->name('admin.new_top_blogger');
    Route::post('/live-search', 'UserController@liveSearch')->name('admin.user_search');
    Route::get('/sticky-post', 'AdminController@stickyPost')->name('admin.sticky_post');
    Route::post('/new-sticky-post', 'AdminController@newStickyPost')->name('admin.new_sticky_post');

    Route::resource('product', 'ProductController', ['names' => [
        'index' => 'product.list',
        'create' => 'product.create',
        'store' => 'product.store',
        'edit' => 'product.edit',
        'update' => 'product.update',
        'destroy' => 'product.destroy'
    ]]);

    /** Shop (boutique) */

    Route::resource('shop/category', 'ProductCategoryController', ['names' => [
        'index' => 'product_category.index',
        'create' => 'product_category.create',
        'store' => 'product_category.store',
        'edit' => 'product_category.edit',
        'update' => 'product_category.update',
        'destroy' => 'product_category.destroy',
        'show' => 'product_category.show'
    ]]);

    Route::post('/vacancy-delete', [
        'uses' => 'ProfileController@deleteVacancy',
        'middleware' => 'employer'
    ]);

    Route::get('vacancy', [
        'uses' => 'VacancyController@indexOrder',
        'as' => 'admin.vacancy'
    ]);

    Route::put('vacancyactive/{id}', [
        'uses' => 'VacancyController@updateActive',
    ])->name('admin.vacancyactive');

    Route::put('vacancyseen/{id}', [
        'uses' => 'VacancyController@updateSeen'
    ])->name('admin.vacancyseen');

    Route::put('/translate/{id}', 'TranslationController@update')->name('admin.trans.update');
    Route::get('/translate/{id}', 'TranslationController@translate')->name('admin.trans.translate');
    Route::post('/translate/{id}', 'TranslationController@store')->name('admin.trans.store');
    Route::get('/translations/{id}', 'TranslationController@translations')->name('admin.trans.index');
    Route::get('/translate/{id}/edit', 'TranslationController@edit')->name('admin.trans.edit');

    Route::get('blog/order', 'BlogController@indexOrder')->name('admin.blog.order');
    Route::put('postseen/{id}', 'BlogController@updateSeen')->name('admin.postseen');
    Route::put('postactive/{id}', 'BlogController@updateActive')->name('admin.postactive');
    Route::put('postlanguage/{id}', 'BlogController@updateLanguage')->name('admin.postlanguage');
    Route::get('post/see/{category}/{id}', 'BlogController@see')->name('admin.post.see');
    Route::resource('blog', 'BlogController', ['except' => ['create', 'store']]);
});

Route::group(['prefix' => LaravelLocalization::setLocale(),'middleware' => [ 'localeSessionRedirect', 'localizationRedirect']], function() {
    // Profile

    Route::resource('profile', 'ProfileController');

    Route::group([
        'prefix' => 'profile',
    ], function () {
        Route::get('post/create', 'BlogController@create')->name('profile.post.create');
        Route::post('post/store', 'BlogController@store')->name('profile.post.store');
        Route::get('profile/vacancies/', 'ProfileController@myVacancies');
        Route::post('/post-delete', ['uses' => 'ProfileController@deletePost', 'middleware' => 'blogger'])->name('profile.post.delete');
        Route::get('/activate-post/{id}', ['uses' => 'ProfileController@activatePost', 'middleware' => 'blogger'])->name('profile.post.activate');
    });

// Home
    Route::get('/', [
        'uses' => 'HomeController@index',
        'as' => 'home'
    ]);


// Business
    Route::get('business/{param}/', 'PageController@show')->name('business.page');

// Blog
    Route::get('blog/tag', 'BlogController@tag');
    Route::get('blog/search', 'BlogController@search');
    Route::get('/articles/{category}/{title}', 'BlogController@show')->name('articles.post.show');


    Route::resource('/articles', 'CategoryController', ['prefix' => 'articles', 'names' => [
        'index' => 'category.index',
        'show' => 'category.show',
        'create' => 'category.create',
        'store' => 'category.store',
        'edit' => 'category.edit',
        'update' => 'category.update',
        'destroy' => 'category.destroy'
    ]]);

    Route::get('/articles/{name}/category/{subcategory}', 'CategoryController@showSubcategory')->name('subcategory.show');


// Fashion-job

    Route::post('fashion-job/search', 'VacancyController@search');
    Route::get('/fashion-job/confirmation', 'VacancyController@confirmation');
    Route::resource('company', 'CompanyController');
    Route::resource('fashion-job', 'VacancyController');

// Boutique

    Route::get('boutique/category/{hierarchy}', 'ProductCategoryController@show')->where('hierarchy', '(.*)?')->name('boutique');
    Route::get('boutique/{hierarchy}/{slug}', 'ProductController@show')->where('hierarchy', '(.*)?')->name('product.show');
    Route::post('/boutique/product/buy', ['uses' => 'ProductController@buyProduct', 'as' => 'product.buy']);
    Route::post('admin/product/images/{id}/delete', ['uses' => 'ProductController@deleteImage', 'as' => 'product.image.delete']);
    Route::post('admin/product/thumb/{id}/delete', ['uses' => 'ProductController@deleteThumb', 'as' => 'product.thumb.delete']);


// User
    Route::get('user/sort/{role}', 'UserController@indexSort');
    Route::get('user/roles', 'UserController@getRoles');
    Route::post('user/roles', 'UserController@postRoles');


// Auth
    Route::controllers([
        'auth' => 'Auth\AuthController',
        'password' => 'Auth\PasswordController'
    ]);

    Route::get('/email-confirmation', 'Auth\AuthController@confirmation');
    Route::get('/resend-email', 'Auth\AuthController@getResend');


// Social networks auth

    Route::get('/facebook/{role?}', ['uses' => 'SocializeController@loginWithFacebook']);
    Route::get('/vkontakte/{role?}', ['uses' => 'SocializeController@loginWithVkontakte']);
    Route::get('/google/{role?}', ['uses' => 'SocializeController@loginWithGoogle']);
    Route::get('/twitter/{role?}', ['uses' => 'SocializeController@loginWithTwitter']);


// Social networks share
    Route::get('/share-twitter/{category}/{slug}/{title}/', function ($category, $slug, $title) {
        $link = URL::to('/') . '/blog/' . $category . '/' . $slug . '/';
        $share = Share::load($link, $title)->twitter();
        return redirect($share);
    });

    Route::get('/share-facebook/{category}/{slug}/{title}/', function ($category, $slug, $title) {
        $link = URL::to('/') . '/blog/' . $category . '/' . $slug . '/';
        $share = Share::load($link, $title)->facebook();
        return redirect($share);
    });

    Route::get('/share-pinterest/{category}/{slug}/{title}/', function ($category, $slug, $title) {
        $link = URL::to('/') . '/blog/' . $category . '/' . $slug . '/';
        $share = Share::load($link, $title)->pinterest();
        return redirect($share);
    });

//Subscribe
    Route::post('subscribe', 'NewsletterController@subscribe');

});

// Ajax actions
Route::post('/like', [
    'uses' => 'BlogController@upLike',
    'middleware' => 'auth'
]);

Route::post('/load-posts', [
    'uses' => 'CategoryController@loadPosts'
]);

Route::post('/load-subcat', [
    'uses' => 'CategoryController@loadSubcategories'
]);

Route::post('/buy-service', [
    'uses' => 'BlogController@buyService'
]);

Route::post('/save-profile', [
    'uses' => 'ProfileController@store',
    'middleware' => 'auth'
]);

Route::post('/save-company', [
    'uses' => 'CompanyController@store',
    'middleware' => 'employer'
]);

Route::post('/delete-company', [
    'uses' => 'CompanyController@destroy',
    'middleware' => 'employer'
]);

Route::post('/profile-posts', [
    'uses' => 'ProfileController@loadPosts',
    'middleware' => 'blogger'
]);

Route::post('/profile-vacancies', [
    'uses' => 'ProfileController@loadVacancies',
    'middleware' => 'employer'
]);

Route::post('/load-vacancies', [
    'uses' => 'VacancyController@loadVacancies'
]);

Route::post('/filter-vacancies', [
    'uses' => 'VacancyController@filterVacancies'
]);

Route::post('/search-vacancies', [
    'uses' => 'VacancyController@searchVacancies'
]);

Route::post('/get-city', [
    'uses' => 'VacancyController@getCity'
]);

Route::post('send-cv', 'VacancyController@sendCV');

/*
|--------------------------------------------------------------------------
| Max Upload File Size filter
|--------------------------------------------------------------------------
|
| Check if a user uploaded a file larger than the max size limit.
| This filter is used when we also use a CSRF filter and don't want
| to get a TokenMismatchException due to $_POST and $_GET being cleared.
|
*/
Route::filter('maxUploadFileSize', function()
{
    // Check if upload has exceeded max size limit
    if (! (Request::isMethod('POST') or Request::isMethod('PUT'))) { return; }
    // Get the max upload size (in Mb, so convert it to bytes)
    $maxUploadSize = 1024 * 1024 * ini_get('post_max_size');
    $contentSize = 0;
    if (isset($_SERVER['HTTP_CONTENT_LENGTH']))
    {
        $contentSize = $_SERVER['HTTP_CONTENT_LENGTH'];
    }
    elseif (isset($_SERVER['CONTENT_LENGTH']))
    {
        $contentSize = $_SERVER['CONTENT_LENGTH'];
    }
    // If content exceeds max size, throw an exception
    if ($contentSize > $maxUploadSize)
    {
        throw new GSVnet\Core\Exceptions\MaxUploadSizeException;
    }
});

app/Http/Controllers/UserController.php
<?php namespace App\Http\Controllers;

use App\Repositories\UserRepository;
use App\Repositories\RoleRepository;
use App\Http\Requests\UserCreateRequest;
use App\Http\Requests\UserUpdateRequest;
use App\Http\Requests\RoleRequest;
use App\Models\User;
use Illuminate\Http\Request;
use App\Models\TopBlogger;
use App\Models\Post;

class UserController extends Controller {

    protected $user_gestion;

    protected $role_gestion;

    /**
     * UserController constructor.
     * @param UserRepository $user_gestion
     * @param RoleRepository $role_gestion
     */
    public function __construct(UserRepository $user_gestion, RoleRepository $role_gestion)
    {
        $this->user_gestion = $user_gestion;
        $this->role_gestion = $role_gestion;

        $this->middleware('admin', ['only' => ['index', 'indexSort', 'indexGo', 'create', 'show', 'updateSeen',
                                    'destroy', 'update', 'weekBlogger', 'liveSearch', 'newTopBlogger']]);
        $this->middleware('ajax', ['only' => 'updateSeen','buyService', 'liveSearch']);
    }

    /**
     * @return mixed
     */
    public function index()
    {
        return $this->indexGo('total');
    }

    /**
     * @param $role
     * @return mixed
     */
    public function indexSort($role)
    {
        return $this->indexGo($role, true);
    }

    /**
     * @param $role
     * @param bool $ajax
     * @return mixed
     */
    private function indexGo($role, $ajax = false)
    {
        $counts = $this->user_gestion->counts();
        $users = $this->user_gestion->index(20, $role);
        $links = $users->setPath('')->render();
        $roles = $this->role_gestion->all();

        if($ajax) {
            return response()->json([
                'view' => view('back.users.table', compact('users', 'links', 'counts', 'roles'))->render(),
                'links' => str_replace('/sort/total', '', $links)
            ]);
        }

        return view('back.users.index', compact('users', 'links', 'counts', 'roles'));
    }

    /**
     * @return mixed
     */
    public function create()
    {
        return view('back.users.create', $this->role_gestion->getAllSelect());
    }

    /**
     * @param UserCreateRequest $request
     * @return mixed
     */
    public function store(UserCreateRequest $request)
    {
        $this->user_gestion->store($request->all());
        return redirect()->route('admin.user.index')->with('ok', 'Created');
    }

    /**
     * @param User $user
     * @return mixed
     */
    public function show(User $user)
    {
        return view('back.users.show',  compact('user'));
    }


    /**
     * @param User $user
     * @return mixed
     */
    public function edit(User $user)
    {
        $roles = $this->role_gestion->getAllSelect()['select'];

        return view('back.users.edit', array_merge(compact('user', 'roles') ));
    }

    /**
     * @param UserUpdateRequest $request
     * @param $user
     * @return mixed
     */
    public function update(UserUpdateRequest $request, $user)
    {
        $this->user_gestion->update($request->all(), $user);

        return redirect()->route('admin.user.index')->with('ok', 'Updated');
    }

    /**
     * @param Request $request
     * @param $user
     * @return mixed
     */
    public function updateSeen(Request $request, $user)
    {
        $this->user_gestion->updateSeen($request->all(), $user->id);

        return response()->json();
    }

    /**
     * @param User $user
     * @return mixed
     */
    public function destroy(User $user)
    {
        User::destroy($user->id);

        return redirect()->route('admin.user.index')->with('ok', 'Destroyed');
    }

    /**
     * @return mixed
     */
    public function getRoles()
    {
        $roles = $this->role_gestion->all();

        return view('back.users.roles', compact('roles'));
    }

    /**
     * @param RoleRequest $request
     * @return mixed
     */
    public function postRoles(RoleRequest $request)
    {
        $this->role_gestion->update($request->except('_token'));

        return redirect('user/roles')->with('ok', 'Ok');
    }

    /**
     * @return mixed
     */
    public function weekBlogger()
    {
        $blogger = TopBlogger::first();

        if ($blogger != null)  {
            $blogger_id = $blogger->user_id;
            $top_blogger = User::find($blogger_id);
            $firstname = $top_blogger->firstname;
            $lastname = $top_blogger->lastname;
            $description = $blogger->description;
        }

        return view('back.users.week-blogger', compact('firstname', 'lastname', 'description'));
    }

    /**
     * @param Request $request
     */
    public function liveSearch(Request $request)
    {
        $search = $request->search;
        $search = addslashes($search);
        $search = htmlspecialchars($search);
        $search = stripslashes($search);
        if($search == ''){
            exit("Начните вводить запрос");
        }

        $result = [];

        if ($request->what == 'week-blogger')
        {
            $users = User::where('firstname', 'LIKE', "%$search%")->get();

            foreach ($users as $user)
            {
                $user = $user->firstname . ' ' . $user->lastname;
                array_push($result, $user);
            }
        } else {
            $posts = Post::where('title', 'LIKE', "%$search%")->get();
            foreach ($posts as $post)
            {
                $post = $post->title;
                array_push($result, $post);
            }

        }

        echo json_encode($result);
    }

    /**
     * @param Request $request
     * @return mixed
     */
    public function newTopBlogger(Request $request)
    {
        $blogger = explode(' ', $request->search);
        $firstname = $blogger[0];
        $lastname = $blogger[1];
        $blogger_id = User::where('firstname', $firstname)->where('lastname', $lastname)->pluck('id');

        $top_blogger = TopBlogger::firstOrNew(array('id' => '1'));
        $top_blogger->user_id = $blogger_id;
        $top_blogger->description = $request->description;
        $top_blogger->save();

        return redirect()->back();
    }

}

resources/views/back/users/edit.blade.php
@extends('back.template')

@section('title', "Edit the user")

@section('main')
	@include('back.partials.entete', ['title' => 'Users', 'icone' => 'user', 'fil' => link_to('user', 'Users') . ' /Edit'])
user/{{ $user->id }}
	<div class="col-sm-12">
		{!! Form::model($user, ['route' => ['admin.user.update', $user->id], 'method' => 'put', 'class' => 'form-horizontal panel']) !!}
            {!! Form::control('text', 0, 'firstname', $errors, 'Firstname') !!}
            {!! Form::control('text', 0, 'lastname', $errors, 'Lastname') !!}
			{!! Form::control('email', 0, 'email', $errors, 'Email') !!}
		<div class="form-group">
			{!! Form::label('role', 'Role:') !!}
			{!! Form::select('role', $roles, $user->role_id, ['class' => 'form-control']) !!}
		</div>
			{!! Form::submit('Update') !!}
		{!! Form::close() !!}
	</div>
@stop

resources/views/back/users/index.blade.php
@extends('back.template')

@section('title', "Users")

@section('head')

<style type="text/css">
  
  .badge {
    padding: 1px 8px 1px;
    background-color: #aaa !important;
  }

</style>

@stop

@section('main')

  @include('back.partials.entete', ['title' => 'Dashboard', 'icone' => 'user', 'fil' => 'Users'])

	@if(session()->has('ok'))
    @include('partials/error', ['type' => 'success', 'message' => session('ok')])
	@endif

  <div class="pull-right link">{!! $links !!}</div>
	<div class="table-responsive">
		<table class="table">
			<thead>
				<tr>
					<th>Firstname</th>
                    <th>Lastname</th>
					<th>Role</th>
					<th>Seen</th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
			  @include('back.users.table')
      </tbody>
		</table>
	</div>
	<div class="pull-right link">{!! $links !!}</div>
@stop

@section('scripts')
  <script>
    $(function() {

      $(document).on('change', ':checkbox', function() {    
        $(this).parents('tr').toggleClass('warning');
        $(this).hide().parent().append('<i class="fa fa-refresh fa-spin"></i>');
        var token = $('input[name="_token"]').val();
        $.ajax({
          url: 'admin/userseen/' + this.value,
          type: 'PUT',
          data: "seen=" + this.checked + "&_token=" + token
        })
        .done(function(response) {
            console.log(response)

          $('.fa-spin').remove();
          $('input[type="checkbox"]:hidden').show();
        })
        .fail(function(response) {
            console.log(response)
          $('.fa-spin').remove();
          var chk = $('input[type="checkbox"]:hidden');
          chk.show().prop('checked', chk.is(':checked') ? null:'checked').parents('tr').toggleClass('warning');
          alert('Fail!');
        });
      });

      // Sorting gestion
      $('#tri').find('a').click(function(e) {
        e.preventDefault();
        // Wait icon
        $('.breadcrumb li').append('<span id="tempo" class="fa fa-refresh fa-spin"></span>');  
        // Buttons aspect
        $('#tri').find('a').removeClass('active');
        // Send ajax
        $.ajax({
          url: 'user/sort/' + $(this).attr('name'),
          type: 'GET',
          dataType: 'json'
        })
        .done(function(data) {
          $('tbody').html(data.view);
          $('.link').html(data.links);
          $('#tempo').remove();
        })
        .fail(function() {
          alert('Fail');
        });        
      });

    });

  </script>

@stop

resources/views/back/users/roles.blade.php
@extends('back.template')

@section('title', "Roles")

@section('main')

  @include('back.partials.entete', ['title' => 'Dashboard', 'icone' => 'user', 'fil' => link_to('user', 'Users') . ' / ' .'Roles'])
	<div class="col-sm-12">
		@if(session()->has('ok'))
			@include('partials/error', ['type' => 'success', 'message' => session('ok')])
		@endif
		{!! Form::open(['url' => 'user/roles', 'method' => 'post', 'class' => 'form-horizontal panel']) !!}	
			@foreach ($roles as $role) 
				{!! Form::control('text', 0, $role->slug, $errors, $role->slug, $role->title) !!}
			@endforeach
			{!! Form::submit(trans('front/form.send')) !!}
		{!! Form::close() !!}
	</div>
@stop

resources/views/back/users/show.blade.php
@extends('back.template')

@section('title', "User")

@section('main')
	@include('back.partials.entete', ['title' => 'Dashboard', 'icone' => 'user', 'fil' => link_to('user', 'Users') . ' / ' . 'Card'])
	<p>{{'Name: ' .  $user->firstname . ' ' . $user->lastname }}</p>
	<p>{{'Enail: ' .  $user->email }}</p>
	<p>{{'Role: ' .  $user->role->title }}</p>
	<p>{{ $user->confirmed ? 'Confirmed' : 'Not confirmed' }}</p>
@stop

resources/views/back/users/sticky_post.blade.php
@extends('back.template')

@section('title', "Sticky post")

@section('main')
    @include('back.partials.entete', ['title' => 'Sticky Post', 'icone' => 'user', 'fil' => link_to('user', 'Posts') . ' / ' . 'Sticky post'])
    <form action="{{route('admin.new_sticky_post')}}" method="post">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <div class="ui-widget">
            <div class="form-group">
                {!! Form::label('post', 'Post title:') !!}
                {!! Form::select('post', $posts, $post, ['class' => 'form-control', 'required' => 'required']) !!}
            </div>
            <div class="form-group">
                <input type="submit" value="Attach" class='btn btn-success'/>
            </div>

        </div>
    </form>
@stop
@section('scripts')
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src="//code.jquery.com/ui/1.9.1/jquery-ui.js"></script>
    <script>
    </script>
@stop

resources/views/back/users/table.blade.php
    @foreach ($users as $user)
		<tr {!! !$user->seen? 'class="warning"' : '' !!}>
			<td class="text-primary"><strong>{{ $user->firstname }}</strong></td>
            <td class="text-primary"><strong>{{ $user->lastname }}</strong></td>
			<td>{{ $user->role->title }}</td>
			<td>{!! Form::checkbox('seen', $user->id, $user->seen) !!}</td>
			<td>{!! link_to_route('admin.user.show', 'See', [$user->id], ['class' => 'btn btn-success btn-block btn']) !!}</td>
			<td>{!! link_to_route('admin.user.edit', 'Edit', [$user->id], ['class' => 'btn btn-warning btn-block']) !!}</td>
			<td>
				{!! Form::open(['method' => 'DELETE', 'route' => ['admin.user.destroy', $user->id]]) !!}
				{!! Form::destroy('Destroy', 'Do you really want to delete it?') !!}
				{!! Form::close() !!}
			</td>
		</tr>
	@endforeach

resources/views/back/users/week-blogger.blade.php
@extends('back.template')

@section('title', "Blogger of week")

@section('main')
    @include('back.partials.entete', ['title' => 'Blogger of week', 'icone' => 'user', 'fil' => link_to('user', 'Users') . ' / ' . 'Blogger of week'])
    {!! Form::open(['route' => 'admin.new_top_blogger', 'method' => 'post']) !!}
        <div class="ui-widget">
            <div class="form-group">
                <label for="search">Name: </label>
                <input id="search" name="search" onkeyup="liveSearch(this.value, 'week-blogger')" class='form-control' autocomplete="off">
            </div>
            <div class="form-group">
                <label for="description">Description: </label>
                <textarea id="description" name="description" class='form-control' autocomplete="off"></textarea>
            </div>
            <input type="submit" value="New" class='btn btn-success'/>
        </div>
    {!! Form::close() !!}
    @if ( isset($firstname) && isset($lastname))
        <h2>Current blogger of week:</h2>
        <p>First Name: {{$firstname}}</p>
        <p>Last Name: {{$lastname}}</p>
        <p>Description: {{$description}}</p>
    @endif
@stop

@section('scripts')
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/ui/1.9.1/jquery-ui.js"></script>
@stop