app/Http/routes.php
<?php

/** Admin **/
Route::group([
    'prefix' => 'admin',
], function () {
    Route::get('dashboard', 'AdminController@admin')->name('admin.dashboard');

    Route::resource('advertisement', 'AdvertisementController');
    Route::resource('slider', 'SliderController');

    Route::resource('user', 'UserController');
    Route::put('admin/userseen/{user}', 'UserController@updateSeen');
    Route::get('week-blogger', 'UserController@weekBlogger')->name('admin.week_blogger');
    Route::post('/new-top-blogger', 'UserController@newTopBlogger')->name('admin.new_top_blogger');
    Route::post('/live-search', 'UserController@liveSearch')->name('admin.user_search');
    Route::get('/sticky-post', 'AdminController@stickyPost')->name('admin.sticky_post');
    Route::post('/new-sticky-post', 'AdminController@newStickyPost')->name('admin.new_sticky_post');

    Route::resource('product', 'ProductController', ['names' => [
        'index' => 'product.list',
        'create' => 'product.create',
        'store' => 'product.store',
        'edit' => 'product.edit',
        'update' => 'product.update',
        'destroy' => 'product.destroy'
    ]]);

    /** Shop (boutique) */

    Route::resource('shop/category', 'ProductCategoryController', ['names' => [
        'index' => 'product_category.index',
        'create' => 'product_category.create',
        'store' => 'product_category.store',
        'edit' => 'product_category.edit',
        'update' => 'product_category.update',
        'destroy' => 'product_category.destroy',
        'show' => 'product_category.show'
    ]]);

    Route::post('/vacancy-delete', [
        'uses' => 'ProfileController@deleteVacancy',
        'middleware' => 'employer'
    ]);

    Route::get('vacancy', [
        'uses' => 'VacancyController@indexOrder',
        'as' => 'admin.vacancy'
    ]);

    Route::put('vacancyactive/{id}', [
        'uses' => 'VacancyController@updateActive',
    ])->name('admin.vacancyactive');

    Route::put('vacancyseen/{id}', [
        'uses' => 'VacancyController@updateSeen'
    ])->name('admin.vacancyseen');

    Route::put('/translate/{id}', 'TranslationController@update')->name('admin.trans.update');
    Route::get('/translate/{id}', 'TranslationController@translate')->name('admin.trans.translate');
    Route::post('/translate/{id}', 'TranslationController@store')->name('admin.trans.store');
    Route::get('/translations/{id}', 'TranslationController@translations')->name('admin.trans.index');
    Route::get('/translate/{id}/edit', 'TranslationController@edit')->name('admin.trans.edit');

    Route::get('blog/order', 'BlogController@indexOrder')->name('admin.blog.order');
    Route::put('postseen/{id}', 'BlogController@updateSeen')->name('admin.postseen');
    Route::put('postactive/{id}', 'BlogController@updateActive')->name('admin.postactive');
    Route::put('postlanguage/{id}', 'BlogController@updateLanguage')->name('admin.postlanguage');
    Route::get('post/see/{category}/{id}', 'BlogController@see')->name('admin.post.see');
    Route::resource('blog', 'BlogController', ['except' => ['create', 'store']]);
});

Route::group(['prefix' => LaravelLocalization::setLocale(),'middleware' => [ 'localeSessionRedirect', 'localizationRedirect']], function() {
    // Profile

    Route::resource('profile', 'ProfileController');

    Route::group([
        'prefix' => 'profile',
    ], function () {
        Route::get('post/create', 'BlogController@create')->name('profile.post.create');
        Route::post('post/store', 'BlogController@store')->name('profile.post.store');
        Route::get('profile/vacancies/', 'ProfileController@myVacancies');
        Route::post('/post-delete', ['uses' => 'ProfileController@deletePost', 'middleware' => 'blogger'])->name('profile.post.delete');
        Route::get('/activate-post/{id}', ['uses' => 'ProfileController@activatePost', 'middleware' => 'blogger'])->name('profile.post.activate');
    });

// Home
    Route::get('/', [
        'uses' => 'HomeController@index',
        'as' => 'home'
    ]);


// Business
    Route::get('business/{param}/', 'PageController@show')->name('business.page');

// Blog
    Route::get('blog/tag', 'BlogController@tag');
    Route::get('blog/search', 'BlogController@search');
    Route::get('/articles/{category}/{title}', 'BlogController@show')->name('articles.post.show');


    Route::resource('/articles', 'CategoryController', ['prefix' => 'articles', 'names' => [
        'index' => 'category.index',
        'show' => 'category.show',
        'create' => 'category.create',
        'store' => 'category.store',
        'edit' => 'category.edit',
        'update' => 'category.update',
        'destroy' => 'category.destroy'
    ]]);

    Route::get('/articles/{name}/category/{subcategory}', 'CategoryController@showSubcategory')->name('subcategory.show');


// Fashion-job

    Route::post('fashion-job/search', 'VacancyController@search');
    Route::get('/fashion-job/confirmation', 'VacancyController@confirmation');
    Route::resource('company', 'CompanyController');
    Route::resource('fashion-job', 'VacancyController');

// Boutique

    Route::get('boutique/category/{hierarchy}', 'ProductCategoryController@show')->where('hierarchy', '(.*)?')->name('boutique');
    Route::get('boutique/{hierarchy}/{slug}', 'ProductController@show')->where('hierarchy', '(.*)?')->name('product.show');
    Route::post('/boutique/product/buy', ['uses' => 'ProductController@buyProduct', 'as' => 'product.buy']);
    Route::post('admin/product/images/{id}/delete', ['uses' => 'ProductController@deleteImage', 'as' => 'product.image.delete']);
    Route::post('admin/product/thumb/{id}/delete', ['uses' => 'ProductController@deleteThumb', 'as' => 'product.thumb.delete']);


// User
    Route::get('user/sort/{role}', 'UserController@indexSort');
    Route::get('user/roles', 'UserController@getRoles');
    Route::post('user/roles', 'UserController@postRoles');


// Auth
    Route::controllers([
        'auth' => 'Auth\AuthController',
        'password' => 'Auth\PasswordController'
    ]);

    Route::get('/email-confirmation', 'Auth\AuthController@confirmation');
    Route::get('/resend-email', 'Auth\AuthController@getResend');


// Social networks auth

    Route::get('/facebook/{role?}', ['uses' => 'SocializeController@loginWithFacebook']);
    Route::get('/vkontakte/{role?}', ['uses' => 'SocializeController@loginWithVkontakte']);
    Route::get('/google/{role?}', ['uses' => 'SocializeController@loginWithGoogle']);
    Route::get('/twitter/{role?}', ['uses' => 'SocializeController@loginWithTwitter']);


// Social networks share
    Route::get('/share-twitter/{category}/{slug}/{title}/', function ($category, $slug, $title) {
        $link = URL::to('/') . '/blog/' . $category . '/' . $slug . '/';
        $share = Share::load($link, $title)->twitter();
        return redirect($share);
    });

    Route::get('/share-facebook/{category}/{slug}/{title}/', function ($category, $slug, $title) {
        $link = URL::to('/') . '/blog/' . $category . '/' . $slug . '/';
        $share = Share::load($link, $title)->facebook();
        return redirect($share);
    });

    Route::get('/share-pinterest/{category}/{slug}/{title}/', function ($category, $slug, $title) {
        $link = URL::to('/') . '/blog/' . $category . '/' . $slug . '/';
        $share = Share::load($link, $title)->pinterest();
        return redirect($share);
    });

//Subscribe
    Route::post('subscribe', 'NewsletterController@subscribe');

});

// Ajax actions
Route::post('/like', [
    'uses' => 'BlogController@upLike',
    'middleware' => 'auth'
]);

Route::post('/load-posts', [
    'uses' => 'CategoryController@loadPosts'
]);

Route::post('/load-subcat', [
    'uses' => 'CategoryController@loadSubcategories'
]);

Route::post('/buy-service', [
    'uses' => 'BlogController@buyService'
]);

Route::post('/save-profile', [
    'uses' => 'ProfileController@store',
    'middleware' => 'auth'
]);

Route::post('/save-company', [
    'uses' => 'CompanyController@store',
    'middleware' => 'employer'
]);

Route::post('/delete-company', [
    'uses' => 'CompanyController@destroy',
    'middleware' => 'employer'
]);

Route::post('/profile-posts', [
    'uses' => 'ProfileController@loadPosts',
    'middleware' => 'blogger'
]);

Route::post('/profile-vacancies', [
    'uses' => 'ProfileController@loadVacancies',
    'middleware' => 'employer'
]);

Route::post('/load-vacancies', [
    'uses' => 'VacancyController@loadVacancies'
]);

Route::post('/filter-vacancies', [
    'uses' => 'VacancyController@filterVacancies'
]);

Route::post('/search-vacancies', [
    'uses' => 'VacancyController@searchVacancies'
]);

Route::post('/get-city', [
    'uses' => 'VacancyController@getCity'
]);

Route::post('send-cv', 'VacancyController@sendCV');

/*
|--------------------------------------------------------------------------
| Max Upload File Size filter
|--------------------------------------------------------------------------
|
| Check if a user uploaded a file larger than the max size limit.
| This filter is used when we also use a CSRF filter and don't want
| to get a TokenMismatchException due to $_POST and $_GET being cleared.
|
*/
Route::filter('maxUploadFileSize', function()
{
    // Check if upload has exceeded max size limit
    if (! (Request::isMethod('POST') or Request::isMethod('PUT'))) { return; }
    // Get the max upload size (in Mb, so convert it to bytes)
    $maxUploadSize = 1024 * 1024 * ini_get('post_max_size');
    $contentSize = 0;
    if (isset($_SERVER['HTTP_CONTENT_LENGTH']))
    {
        $contentSize = $_SERVER['HTTP_CONTENT_LENGTH'];
    }
    elseif (isset($_SERVER['CONTENT_LENGTH']))
    {
        $contentSize = $_SERVER['CONTENT_LENGTH'];
    }
    // If content exceeds max size, throw an exception
    if ($contentSize > $maxUploadSize)
    {
        throw new GSVnet\Core\Exceptions\MaxUploadSizeException;
    }
});

resources/views/back/blog/create.blade.php
@extends('front.template')

@section('title', trans('back/post_propose.propose-post'))

@section('main')
    <section class="fjob-list-section profile-page clearfix">
        @include('back.profile.profile-left')
        <div class="profile-right clearfix">
            {!! Form::open(['route' => 'profile.post.store', 'method' => 'post', "class" => "propose-post-form", 'enctype'=>"multipart/form-data"]) !!}
            {!! Form::hidden('user_id', $user_id) !!}
            <div class="rules-block">
                {!! Form::checkbox('is_commercial','1', '', ['class' => 'checkbox-filter profile-checkbox', 'id' => 'is_commercial']) !!}
                {!! Form::label('is_commercial', trans('back/post_propose.are-commercial')) !!}
            </div>
            {!! Form::text('title', '', ['class' => 'block-input-profile block-input-profile-post-name', 'placeholder' => trans('back/post_propose.post-name'), 'required' => 'required']) !!}
            <span class="post-choose-category">{{trans('back/post_propose.choose-category')}}</span>
            <div class="post-categories-block">
                @foreach($categories as $category)
                    @if ($category->name !== 'video')
                        {!! Form::checkbox("$category->name","$category->id", '', ['class' => 'checkbox-filter profile-checkbox post-main-category-checkbox', 'id' => "$category->name"]) !!}
                        {!! Form::label("$category->name", trans('front/category.'.$category->name)) !!}
                        <?php $subcategories = explode(',', $category->subcategories); ?>
                        @if (count($subcategories) > 0)
                            <div class="subs-block fashion-subs-block">
                                @for ($i = 0;$i < count($subcategories); $i++)
                                        {!! Form::checkbox("$subcategories[$i]","$subcategories[$i]", '', ['class' => 'checkbox-filter profile-checkbox post-sub-category-checkbox', 'id' => "$subcategories[$i]"]) !!}
                                        {!! Form::label("$subcategories[$i]", trans('front/subcategory.'.trim($subcategories[$i]))) !!}
                                @endfor
                            </div>
                        @endif
                    @elseif ($category->name == 'video')
                        {!! Form::checkbox('post-video',"$category->id", '', ['class' => 'checkbox-filter profile-checkbox post-main-category-checkbox', 'id' => 'post-video']) !!}
                        {!! Form::label('post-video', trans('front/category.video')) !!}
                    @endif
                @endforeach
                <div class="post-fields">
                    <div class="clearfix tagsinput tagsinput-videolink">
                        <label for="post-videolink">{{trans('back/post_propose.video-url')}} <span>(YouTube/Vimeo)</span></label>
                        {!! Form::text('post-videolink', '', ['id' => 'post-videolink']) !!}
                    </div>
                </div>
                <div class="post-image-outer">
                    <div class="post-image-inner post-preview" id="post-preview">
                        <img src="/img/post-default.jpg" alt="Post name">
                    </div>
                </div>
                {!! Form::file('thumb', ['class' => 'post-preview-file', 'id' => 'post-preview-file'])!!}
				<span class="post-preview-text">
					{{trans('back/post_propose.recommended-dimensions')}} 1660 x 740 px<br>
                    {{trans('back/post_propose.size-less')}} 600 kb
				</span>
                <span class="write-post-label">{{trans('back/post_propose.write-post')}}</span>
                <div class="text-edit-container">
                    {!! Form::textarea('content', '', ['required' => 'required'] ) !!}
                </div>
                <div class="post-fields">
                    <div class="clearfix tagsinput">
                        {!! Form::label('tags', trans('back/post_propose.tags')) !!}
                        {!! Form::text('tags', '', ['id' => 'tags']) !!}
                    </div>
                    <div class="clearfix">
                        {!! Form::label('photographer', trans('back/post_propose.photographer')) !!}
                        {!! Form::text('photographer', '', ['id' => 'photographer']) !!}
                    </div>
                    <div class="clearfix">
                        {!! Form::label('styling', trans('back/post_propose.styling-makeup')) !!}
                        {!! Form::text('styling', '', ['id' => 'styling']) !!}
                    </div>
                    <div class="clearfix">
                        {!! Form::label('outfit', trans('back/post_propose.outfit')) !!}
                        {!! Form::text('outfit', '', ['id' => 'outfit']) !!}
                    </div>
                    <div class="clearfix">
                        {!! Form::label('location', trans('back/post_propose.location')) !!}
                        {!! Form::text('location', '', ['id' => 'location']) !!}
                    </div>
                    <div class="clearfix post-fields-website">
                        {!! Form::label('website', trans('back/post_propose.website')) !!}
                        {!! Form::text('website', '', ['id' => 'website']) !!}
                    </div>
                </div>
                <div class="clearfix">
                    <input type="submit" value="{{trans('back/post_propose.send-post')}}" class="send-post-button" id="send-post-button">
                </div>
                {!! Form::hidden('category_id', '', ['id' => 'category_id']) !!}
                {!! Form::hidden('subcategory', '', ['id' => 'subcategory']) !!}
                {!! Form::close() !!}
            </div>
        </div>
            <div class="filter-overlay filter-overlay-profile" style="opacity: 0;"></div>
    </section>
@stop

@section('scripts')
	{!! HTML::script('ckeditor/ckeditor.js') !!}
    <script src="{{asset('js/ajax.js')}}"></script>

	<script>
        var config = {
            language: '{{ config('app.locale') }}',
            height: 300,
            filebrowserBrowseUrl: '{!! url($url) !!}',
            toolbarGroups: [
                { name: 'clipboard',   groups: [ 'clipboard', 'undo' ] },
                { name: 'editing',     groups: [ 'find', 'selection', 'spellchecker' ] },
                { name: 'links' },
                { name: 'insert' },
                { name: 'forms' },
                { name: 'tools' },
                { name: 'document',	   groups: [ 'mode', 'document', 'doctools' ] },
                { name: 'others' },
                //'/',
                { name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] },
                { name: 'paragraph',   groups: [ 'list', 'indent', 'blocks', 'align', 'bidi' ] },
                { name: 'styles' },
                { name: 'colors' }
            ]
        };
        CKEDITOR.replace( 'content', config);
  </script>
@stop

resources/views/back/blog/edit.blade.php
@extends('front.template')

@section('title', "Edit the post")

@section('main')
    <section class="fjob-list-section profile-page clearfix">
        <div class="profile-right clearfix">
            {!! Form::open(['route' => ['admin.blog.update', $post->id], 'method' => 'put', "class" => "propose-post-form", 'enctype'=>"multipart/form-data"]) !!}
                {!! Form::hidden('user_id', $post->user_id) !!}
                {!! Form::text('title', "$post->title", ['class' => 'block-input-profile block-input-profile-post-name', 'placeholder' => 'Name of the post', 'required' => 'required']) !!}
                <span class="post-choose-category">Choose the category</span>
                <div class="post-categories-block">
                    @foreach($categories as $category)
                        @if ($category->name !== 'Video')
                            {!! Form::checkbox($category->name, $category->id, '', ['class' => 'checkbox-filter profile-checkbox post-main-category-checkbox', 'id' => $category->name]) !!}
                            {!! Form::label($category->name, ucfirst($category->name)) !!}
                            <?php $subcategories = explode(',', $category->subcategories); ?>
                            @if (count($subcategories) > 0)
                                <div class="subs-block fashion-subs-block">
                                    @for ($i = 0;$i < count($subcategories); $i++)
                                        {!! Form::checkbox($subcategories[$i],$subcategories[$i], '', ['class' => 'checkbox-filter profile-checkbox post-sub-category-checkbox', 'id' => $subcategories[$i]]) !!}
                                        {!! Form::label($subcategories[$i], ucfirst(trim($subcategories[$i]))) !!}
                                    @endfor
                                </div>
                            @endif
                        @elseif($category->name == 'Video')
                            {!! Form::checkbox('post-video','Video', '', ['class' => 'checkbox-filter profile-checkbox post-main-category-checkbox', 'id' => 'post-video']) !!}
                            {!! Form::label('post-video', 'Video') !!}
                        @endif
                    @endforeach
                    <div class="post-fields">
                        <div class="clearfix tagsinput tagsinput-videolink">
                            <label for="post-videolink">Video URL <span>(YouTube/Vimeo)</span></label>
                            {!! Form::text('post-videolink', '$post->video', ['id' => 'post-videolink']) !!}
                        </div>
                    </div>
                    <div class="post-image-outer">
                        <div class="post-image-inner post-preview" id="post-preview">
                            @if ($post['thumb'] !== '')
                                <img src="/img/uploads/thumbs/fourth/{{$post->user_id}}/{{$post->thumb}}" />
                            @else
                                <img src="/img/post-default.jpg" alt="Post name">
                            @endif

                        </div>
                    </div>
                    {!! Form::file('thumb', ['class' => 'post-preview-file', 'id' => 'post-preview-file'])!!}
                    <span class="post-preview-text">
                        Recommended demensions 1660 x 740 px<br>
                        Size weight less then 600 kb
                    </span>
                    <span class="write-post-label">Write your post</span>
                    <div class="text-edit-container">
                        {!! Form::textarea('content', "$post->content", ['required' => 'required'] ) !!}
                    </div>
                        <span class="write-post-label">Write description for SEO:</span>
                        <div class="text-edit-container">
                            {!! Form::textarea('description', "$post->description") !!}
                        </div>

                        <div class="post-fields">
                            {!! Form::label('keywords', 'Keywords') !!}
                            {!! Form::text('keywords', "$post->keywords", ['id' => 'keywords']) !!}
                        </div>
                    <div class="post-fields">
                        <div class="clearfix">
                            {!! Form::label('photographer', 'Photographer') !!}
                            {!! Form::text('photographer', "$post->photographer", ['id' => 'photographer']) !!}
                        </div>
                        <div class="clearfix">
                            {!! Form::label('styling', 'Styling / Makeup') !!}
                            {!! Form::text('styling', "$post->styling", ['id' => 'styling']) !!}
                        </div>
                        <div class="clearfix">
                            {!! Form::label('outfit', 'Outfit') !!}
                            {!! Form::text('outfit', "$post->outfit", ['id' => 'outfit']) !!}
                        </div>
                        <div class="clearfix">
                            {!! Form::label('location', 'Location') !!}
                            {!! Form::text('location', "$post->location", ['id' => 'location']) !!}
                        </div>
                        <div class="clearfix post-fields-website">
                            {!! Form::label('website', 'Website') !!}
                            {!! Form::text('website', "$post->website", ['id' => 'website']) !!}
                        </div>
                    </div>
                    <div class="clearfix">
                        <input type="submit" value="Send post" class="send-post-button" id="send-post-button">
                    </div>
                    {!! Form::hidden('category_id', "$post->category_id", ['id' => 'category_id']) !!}
                    {!! Form::hidden('subcategory', "$post->subcategory", ['id' => 'subcategory']) !!}
                {!! Form::close() !!}
            </div>
        </div>
        <div class="filter-overlay filter-overlay-profile" style="opacity: 0;"></div>
    </section>
@stop

@section('scripts')
    {!! HTML::script('ckeditor/ckeditor.js') !!}
    <script>
        var config = {
            language: '{{ App::getLocale() }}',
            height: 300,
            filebrowserBrowseUrl: '{!! url($url) !!}',
            toolbarGroups: [
                { name: 'clipboard',   groups: [ 'clipboard', 'undo' ] },
                { name: 'editing',     groups: [ 'find', 'selection', 'spellchecker' ] },
                { name: 'links' },
                { name: 'insert' },
                { name: 'forms' },
                { name: 'tools' },
                { name: 'document',	   groups: [ 'mode', 'document', 'doctools' ] },
                { name: 'others' },
                //'/',
                { name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] },
                { name: 'paragraph',   groups: [ 'list', 'indent', 'blocks', 'align', 'bidi' ] },
                { name: 'styles' },
                { name: 'colors' }
            ]
        };
        CKEDITOR.replace( 'content', config);
    </script>
@stop

resources/views/back/blog/index.blade.php
@extends('back.template')

@section('title', "All posts")

@section('main')

  @include('back.partials.entete', ['title' => 'Dashboard' . link_to_route('profile.post.create', 'Add', [], ['class' => 'btn btn-info pull-right']), 'icone' => 'pencil', 'fil' => 'Posts'])

	@if(session()->has('ok'))
    @include('partials/error', ['type' => 'success', 'message' => session('ok')])
	@endif

  <div class="row col-lg-12">
    <div class="pull-right link">{!! $links !!}</div>
  </div>

  <div class="row col-lg-12">
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th>
              Title
            </th>
            <th>
              Date
            </th>
            <th>
              Published
            </th>
              <th>
                Author
              </th>
              <th>
                Language
              </th>
              <th>
                Seen
              </th>
          </tr>
        </thead>
        <tbody>
          @foreach ($posts as $post)
            <tr {!! !$post->seen && (session('statut') == 'admin' ||  session('statut') == 'redac') ? 'class="warning"' : '' !!}>
              <td class="text-primary"><strong>{{ $post->title }}</strong></td>
              <td>{{ $post->created_at }}</td>
              <td>{!! Form::checkbox('active', $post->id, $post->active) !!}</td>
              <td>{{ $post->firstname . ' ' . $post->lastname }}</td>
              <td>{!! Form::select('language', $languages, $post->language_id, ['class' => 'form-control', 'id' => $post->id]) !!}</td>
              <td>{!! Form::checkbox('seen', $post->id, $post->seen) !!}</td>
              @if ($post->active == 0)
                <td>{!! link_to_route('admin.post.see', 'See', [$post->name, $post->id], ['class' => 'btn btn-success btn-block btn']) !!}</td>
              @else
                <td>{!! link_to_route('articles.post.show', 'See', [$post->name, $post->slug], ['class' => 'btn btn-success btn-block btn']) !!}</td>
              @endif
              <td>{!! link_to_route('admin.blog.edit', 'Edit', [$post->id], ['class' => 'btn btn-warning btn-block']) !!}</td>
                @if ($post->language_id !== null)
                    <td>{!! link_to_route('admin.trans.translate','Translate', $post->id,['class' => 'btn btn-info btn-block btn']) !!}</td>
                @endif
              <td>
                {!! Form::open(['method' => 'DELETE', 'route' => ['admin.blog.destroy', $post->id]]) !!}
                {!! Form::destroy('Destroy', 'Do you really want to delete it?') !!}
                {!! Form::close() !!}
              </td>
            </tr {!! !$post->seen && (session('statut') == 'admin' ||  session('statut') == 'redac') ? 'class="warning"' : '' !!}>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>
  <div class="row col-lg-12">
    <div class="pull-right link">{!! $links !!}</div>
  </div>
@stop

@section('scripts')

  <script>

    $(function() {

      // Language action
      $("select[name='language']").on('change', function() {
        var token = $('input[name="_token"]').val();
        var url = '{{ route('admin.postlanguage', ':id') }}';
        url = url.replace(':id', $(this).attr('id'));
        $.ajax({
          url: url,
          type: 'PUT',
          data: "language_id=" + $(this).val() + "&_token=" + token
        }).done(function() {

        }).fail(function() {

        });
      });


      // Seen gestion
      $(document).on('change', ':checkbox[name="seen"]', function() {
        $(this).parents('tr').toggleClass('warning');
        $(this).hide().parent().append('<i class="fa fa-refresh fa-spin"></i>');
        var token = $('input[name="_token"]').val();
        var url = '{{ route('admin.postseen', ':id') }}';
        url = url.replace(':id', this.value);
        $.ajax({
                  url: url,
                  type: 'PUT',
                  data: "seen=" + this.checked + "&_token=" + token
                })
                .done(function() {
                  $('.fa-spin').remove();
                  $('input:checkbox[name="seen"]:hidden').show();
                })
                .fail(function() {
                  $('.fa-spin').remove();
                  chk = $('input:checkbox[name="seen"]:hidden');
                  chk.show().prop('checked', chk.is(':checked') ? null:'checked').parents('tr').toggleClass('warning');
                  alert('{{ trans('back/blog.fail') }}');
                });
      });

      // Active gestion
      $(document).on('change', ':checkbox[name="active"]', function() {
        $(this).hide().parent().append('<i class="fa fa-refresh fa-spin"></i>');
        var token = $('input[name="_token"]').val();
        var url = '{{ route('admin.postactive', ':id') }}';
        url = url.replace(':id', this.value);
        $.ajax({
                  url: url,
                  type: 'PUT',
                  data: "active=" + this.checked + "&_token=" + token
                })
                .done(function() {
                  $('.fa-spin').remove();
                  $('input:checkbox[name="active"]:hidden').show();
                })
                .fail(function() {
                  $('.fa-spin').remove();
                  chk = $('input:checkbox[name="active"]:hidden');
                  chk.show().prop('checked', chk.is(':checked') ? null:'checked').parents('tr').toggleClass('warning');
                  alert('{{ trans('back/blog.fail') }}');
                });
      });


    });

  </script>

@stop